apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  annotations:
    field.cattle.io/creatorId: user-29jdm
  creationTimestamp: '2023-10-06T03:23:10Z'
  finalizers:
    - wrangler.cattle.io/provisioning-cluster-remove
    - wrangler.cattle.io/rke-cluster-remove
    - wrangler.cattle.io/cloud-config-secret-remover
  generation: 3
  managedFields:
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"wrangler.cattle.io/provisioning-cluster-remove": {}
            v:"wrangler.cattle.io/rke-cluster-remove": {}
        f:spec:
          .: {}
          f:cloudCredentialSecretName: {}
          f:kubernetesVersion: {}
          f:localClusterAuthEndpoint: {}
          f:rkeConfig:
            .: {}
            f:chartValues:
              .: {}
              f:rke2-calico: {}
            f:etcd:
              .: {}
              f:snapshotRetention: {}
              f:snapshotScheduleCron: {}
            f:machineGlobalConfig:
              .: {}
              f:cni: {}
              f:disable-kube-proxy: {}
              f:etcd-expose-metrics: {}
            f:machinePoolDefaults: {}
            f:machinePools: {}
            f:machineSelectorConfig: {}
            f:registries: {}
            f:upgradeStrategy:
              .: {}
              f:controlPlaneConcurrency: {}
              f:controlPlaneDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
              f:workerConcurrency: {}
              f:workerDrainOptions:
                .: {}
                f:deleteEmptyDirData: {}
                f:disableEviction: {}
                f:enabled: {}
                f:force: {}
                f:gracePeriod: {}
                f:ignoreDaemonSets: {}
                f:ignoreErrors: {}
                f:postDrainHooks: {}
                f:preDrainHooks: {}
                f:skipWaitForDeleteTimeoutSeconds: {}
                f:timeout: {}
      manager: rancher
      operation: Update
      time: '2023-10-06T03:23:10Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            v:"wrangler.cattle.io/cloud-config-secret-remover": {}
      manager: rancher-v2.7.8-secret-migrator
      operation: Update
      time: '2023-10-06T03:23:10Z'
    - apiVersion: provisioning.cattle.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:agentDeployed: {}
          f:clientSecretName: {}
          f:clusterName: {}
          f:conditions: {}
          f:observedGeneration: {}
          f:ready: {}
      manager: rancher
      operation: Update
      subresource: status
      time: '2023-10-06T03:28:57Z'
  name: cluster645
  namespace: fleet-default
  resourceVersion: '14370'
  uid: 7a4bedcd-4979-4b46-a65f-d52d91fc80c9
spec:
  cloudCredentialSecretName: cattle-global-data:cc-nvmbn
  kubernetesVersion: v1.26.8+rke2r1
  localClusterAuthEndpoint: {}
  rkeConfig:
    chartValues:
      rke2-calico: {}
    etcd:
      snapshotRetention: 5
      snapshotScheduleCron: 0 */5 * * *
    machineGlobalConfig:
      cni: calico
      disable-kube-proxy: false
      etcd-expose-metrics: false
    machinePoolDefaults: {}
    machinePools:
      - controlPlaneRole: true
        dynamicSchemaSpec: >-
          {"resourceFields":{"accessKey":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          Access
          Key"},"ami":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          machine
          image"},"blockDurationMinutes":{"type":"string","default":{"stringValue":"0","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          spot instance duration in minutes (60, 120, 180, 240, 300, or
          360)"},"deviceName":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          root device
          name"},"encryptEbsVolume":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Encrypt
          the EBS volume using the AWS Managed
          CMK"},"endpoint":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Optional
          endpoint URL (hostname only or fully qualified
          URI)"},"httpEndpoint":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Enables
          or disables the HTTP metadata endpoint on your
          instances"},"httpTokens":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"The
          state of token usage for your instance metadata
          requests."},"iamInstanceProfile":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          IAM Instance
          Profile"},"insecureTransport":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Disable
          SSL when sending
          requests"},"instanceType":{"type":"string","default":{"stringValue":"t2.micro","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          instance
          type"},"keypairName":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          keypair to use; requires
          --amazonec2-ssh-keypath"},"kmsKey":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Custom
          KMS key using the AWS Managed
          CMK"},"monitoring":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Set
          this flag to enable CloudWatch
          monitoring"},"openPort":{"type":"array[string]","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"nullable":true,"create":true,"update":true,"description":"Make
          the specified port number accessible from the
          Internet"},"privateAddressOnly":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Only
          use a private IP
          address"},"region":{"type":"string","default":{"stringValue":"us-east-1","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          region"},"requestSpotInstance":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Set
          this flag to request spot
          instance"},"retries":{"type":"string","default":{"stringValue":"5","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Set
          retry count for recoverable failures (use -1 to
          disable)"},"rootSize":{"type":"string","default":{"stringValue":"16","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          root disk size (in
          GB)"},"secretKey":{"type":"password","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          Secret
          Key"},"securityGroup":{"type":"array[string]","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":["rancher-nodes"]},"nullable":true,"create":true,"update":true,"description":"AWS
          VPC security
          group"},"securityGroupReadonly":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Skip
          adding default rules to security
          groups"},"sessionToken":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          Session
          Token"},"spotPrice":{"type":"string","default":{"stringValue":"0.50","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          spot instance bid price (in
          dollar)"},"sshKeyContents":{"type":"password","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"File
          contents for
          sshKeyContents"},"sshUser":{"type":"string","default":{"stringValue":"ubuntu","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Set
          the name of the ssh
          user"},"subnetId":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          VPC subnet
          id"},"tags":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          Tags (e.g.
          key1,value1,key2,value2)"},"useEbsOptimizedInstance":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Create
          an EBS optimized
          instance"},"usePrivateAddress":{"type":"boolean","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Force
          the usage of private IP
          address"},"userdata":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"File
          contents for
          userdata"},"volumeType":{"type":"string","default":{"stringValue":"gp2","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"Amazon
          EBS volume
          type"},"vpcId":{"type":"string","default":{"stringValue":"","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          VPC
          id"},"zone":{"type":"string","default":{"stringValue":"a","intValue":0,"boolValue":false,"stringSliceValue":null},"create":true,"update":true,"description":"AWS
          zone for instance (i.e. a,b,c,d,e)"}}}
        etcdRole: true
        machineConfigRef:
          kind: Amazonec2Config
          name: nc-cluster645-pool1-z5v4t
        name: pool1
        quantity: 1
        unhealthyNodeTimeout: 0s
        workerRole: true
    machineSelectorConfig:
      - config:
          protect-kernel-defaults: false
    registries: {}
    upgradeStrategy:
      controlPlaneConcurrency: '1'
      controlPlaneDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
      workerConcurrency: '1'
      workerDrainOptions:
        deleteEmptyDirData: true
        disableEviction: false
        enabled: false
        force: false
        gracePeriod: -1
        ignoreDaemonSets: true
        ignoreErrors: false
        postDrainHooks: null
        preDrainHooks: null
        skipWaitForDeleteTimeoutSeconds: 0
        timeout: 120
status:
  agentDeployed: true
  clientSecretName: cluster645-kubeconfig
  clusterName: c-m-wpdxd8lc
  conditions:
    - lastUpdateTime: '2023-10-06T03:28:41Z'
      status: 'False'
      type: Reconciling
    - lastUpdateTime: '2023-10-06T03:23:10Z'
      status: 'False'
      type: Stalled
    - lastUpdateTime: '2023-10-06T03:28:41Z'
      status: 'True'
      type: Created
    - lastUpdateTime: '2023-10-06T03:28:57Z'
      status: 'True'
      type: RKECluster
    - lastUpdateTime: '2023-10-06T03:23:10Z'
      status: 'True'
      type: BackingNamespaceCreated
    - lastUpdateTime: '2023-10-06T03:23:10Z'
      status: 'True'
      type: DefaultProjectCreated
    - lastUpdateTime: '2023-10-06T03:23:10Z'
      status: 'True'
      type: SystemProjectCreated
    - lastUpdateTime: '2023-10-06T03:23:10Z'
      status: 'True'
      type: InitialRolesPopulated
    - lastUpdateTime: '2023-10-06T03:23:11Z'
      status: 'True'
      type: CreatorMadeOwner
    - lastUpdateTime: '2023-10-06T03:28:57Z'
      status: 'True'
      type: Updated
    - lastUpdateTime: '2023-10-06T03:28:57Z'
      status: 'True'
      type: Provisioned
    - lastUpdateTime: '2023-10-06T03:28:57Z'
      status: 'True'
      type: Ready
    - lastUpdateTime: '2023-10-06T03:23:14Z'
      status: 'True'
      type: NoDiskPressure
    - lastUpdateTime: '2023-10-06T03:23:14Z'
      status: 'True'
      type: NoMemoryPressure
    - lastUpdateTime: '2023-10-06T03:23:14Z'
      status: 'True'
      type: SecretsMigrated
    - lastUpdateTime: '2023-10-06T03:23:14Z'
      status: 'True'
      type: ServiceAccountSecretsMigrated
    - lastUpdateTime: '2023-10-06T03:23:14Z'
      status: 'True'
      type: RKESecretsMigrated
    - lastUpdateTime: '2023-10-06T03:23:14Z'
      status: 'True'
      type: ACISecretsMigrated
    - lastUpdateTime: '2023-10-06T03:28:39Z'
      status: 'True'
      type: Connected
    - lastUpdateTime: '2023-10-06T03:28:12Z'
      status: 'True'
      type: GlobalAdminsSynced
    - lastUpdateTime: '2023-10-06T03:28:24Z'
      status: 'True'
      type: SystemAccountCreated
    - lastUpdateTime: '2023-10-06T03:28:26Z'
      status: 'True'
      type: AgentDeployed
    - lastUpdateTime: '2023-10-06T03:28:41Z'
      status: 'True'
      type: Waiting
  observedGeneration: 3
  ready: true
